services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - CatalogDb
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DatabaseSettings__ConnectionString=mongodb://CatalogDb:27017
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__ProductsCollectionName=Products
      - DatabaseSettings__ProductBrandsCollectionName=ProductBrands
      - DatabaseSettings__ProductTypesCollectionName=ProductTypes

  CatalogDb:
    image: mongo
    container_name: catalogdb
    ports:
      - "27017:27017"
    volumes:
      - catalogdbdata:/data/db
  basketdb:
   image: redis:alpine
   container_name: basketdb
   restart: always
   ports:
     - "6379:6379"
  postgresdb:
    image: postgres:alpine
    container_name: discountDb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: discountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d discountDb"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ecommerce.com
      PGADMIN_DEFAULT_PASSWORD: Password123!
    ports:
    - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
     
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/Basket/Basket.API/Dockerfile
    ports:
    - "8081:8080"
    depends_on:
      - basketdb
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CacheSettings__ConnectionString=basketdb:6379
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "8080:8080"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: services/Discount/Discount.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings=server=discountDb;port=5432;database=discountDb;user id=admin;password=Password123!
    container_name: discount.api  
    depends_on:
     discountDb:
      condition: service_healthy
    ports:
    - "8082:8080"
volumes:
  catalogdbdata:
  portainer_data:
  postgres_data:
  pgadmin_data:
   
